#!/usr/bin/env bash

SCRIPT_HELP=0
INPUT_FILE=0
OUTPUT_FILE=0

function avi2mp4_print_help() {
  cat <<EOF
Encodes an AVI video to a high-quality H.264 MP4 video

USAGE:
    avi2mp4 -i input.avi -o output.mp4

OPTIONS:
    -i, --input
            AVI input file to encode
    -o, --output
            MP4 output file path
    -h, --help
            Show this help
EOF
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -i|--input)
      INPUT_FILE="$2"
      shift
      shift
      ;;
    -o|--output)
      OUTPUT_FILE="$2"
      shift
      shift
      ;;
    -h|--help)
      SCRIPT_HELP=1
      shift
      shift
      ;;
    --default)
      DEFAULT=YES
      shift
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done

set -- "${POSITIONAL[@]}"

if [ "${SCRIPT_HELP}" -eq 1 ];
then
  avi2mp4_print_help
  exit 0
fi

if [ "${INPUT_FILE}" = "0" ] || [ "${OUTPUT_FILE}" = "0" ];
then
  avi2mp4_print_help
  exit 1
fi

ffmpeg -i "${INPUT_FILE}" \
  # Codec
  -c:v libx264 \

  # Quality settings
  -preset slow \
  -crf 15 \
  
  # Map video track
  -map 0:0 \

  # Map audio tracks
  -map 0:1 \
  -map 0:2 \

  # First audio track (system sound)
  -c:a:0 aac \
  -b:a:0 256k \

  # Second audio track (voice)
  -c:a:1 aac \
  -b:a:1 256k \

  # Video format
  -vf format=yuv420p \

  # Move flags to start for faster skipping
  -movflags +faststart \

  "${OUTPUT_FILE}"
